workflows:
  android-workflow:
    name: Android Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Generate App Icons
        script: |
          # iOS 폴더가 없어도 에러 없이 안드로이드 아이콘만 생성하도록 실행
          flutter pub run flutter_launcher_icons
      - name: Flutter build APK
        script: |
          # 버전을 1.0.1+5로 올려서 새 앱으로 인식하게 함
          flutter build apk --release --build-name=1.0.1 --build-number=5
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@example.com # 본인 이메일로 수정
