workflows:
  android-workflow:
    name: Build Android APK
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Initialize Project
        script: |
          flutter create .
      - name: Get Dependencies
        script: |
          flutter pub get
      - name: Generate Splash Screen
        script: |
          # [중요] 스플래시 이미지를 시스템 파일로 강제 변환
          flutter pub run flutter_native_splash:create || true
      - name: Build APK
        script: |
          # 스플래시가 적용된 최종 APK 빌드
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
