workflows:
  bike-fit-build:
    name: Bike Fit Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Project Initialize
        script: |
          # 비어있는 안드로이드 구조를 생성합니다.
          flutter create . --platforms android
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
