workflows:
  android-release:
    name: OverTheBikeFit Build
    environment:
      flutter: stable
    scripts:
      - name: Reconstruct Project and Fix Icon Path
        script: |
          # 안드로이드 구조 재생성 및 V2 임베딩 적용
          flutter create --platforms android .
          
          # 권한 파일 강제 주입 (meta-data 포함하여 V1 오류 방지)
          mkdir -p android/app/src/main
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
              <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
              <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
              <application
                  android:label="OverTheBikeFit"
                  android:name="\${applicationName}"
                  android:icon="@mipmap/ic_launcher">
                  <meta-data android:name="flutterEmbedding" android:value="2" />
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
      - name: Get packages and Generate Assets
        script: |
          flutter pub get
          # 아이콘과 스플래시 생성
          flutter pub run flutter_launcher_icons:main
          flutter pub run flutter_native_splash:create
      - name: Build APK
        script: |
          # 리소스 누락 에러 방지를 위한 클린 빌드
          flutter build apk --release --build-name=2.1.0 --build-number=2100
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
