workflows:
  over_the_bike_fit:
    name: Over The Bike Fit Build
    instance_type: mac_mini_m2
    max_build_duration: 45

    environment:
      flutter: stable

    scripts:
      - flutter pub get

      - |
        mkdir -p android/gradle/wrapper
        echo "distributionBase=GRADLE_USER_HOME" > android/gradle/wrapper/gradle-wrapper.properties
        echo "distributionPath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
        echo "zipStoreBase=GRADLE_USER_HOME" >> android/gradle/wrapper/gradle-wrapper.properties
        echo "zipStorePath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
        echo "distributionUrl=https://services.gradle.org/distributions/gradle-8.5-all.zip" >> android/gradle/wrapper/gradle-wrapper.properties

        echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
        echo "sdk.dir=$ANDROID_HOME" >> android/local.properties

      - flutter clean
      - flutter build apk --release --split-per-abi

    artifacts:
      - build/**/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
