workflows:
  android-release:
    name: OverTheBikeFit Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.over.bikefit"
    scripts:
      - echo "🚴 Building OverTheBikeFit APK..."
      - flutter clean
      - flutter pub get
      - flutter pub run flutter_launcher_icons
      - flutter pub run flutter_native_splash:create
      - flutter build apk --release
      - echo "✅ APK build completed!"
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
