workflows:
  android-release:
    name: OverTheBikeFit Build
    environment:
      flutter: stable
    scripts:
      - name: Reconstruct Project and Fix V1 Embedding
        script: |
          # 안드로이드 프로젝트 구조 재생성
          flutter create --platforms android .
          
          # 최신 v2 임베딩 규격으로 권한 파일 강제 주입
          mkdir -p android/app/src/main
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
              <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
              <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
              <application
                  android:label="OverTheBikeFit"
                  android:name="\${applicationName}"
                  android:icon="@mipmap/launcher_icon">
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2" />
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
      - name: Get packages
        script: flutter pub get
      - name: Generate Assets
        script: |
          flutter pub run flutter_launcher_icons:main
          flutter pub run flutter_native_splash:create
      - name: Build APK
        script: |
          # 빌드 번호를 2000으로 올려서 완전히 새 앱으로 배포
          flutter build apk --release --build-name=2.0.0 --build-number=2000
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
