workflows:
  android-workflow:
    name: Android Release Build
    working_directory: . 
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Recreate Android Folder
        script: |
          flutter clean
          rm -rf android
          flutter create --platforms android .
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          # SDK 버전을 강제로 26으로 지정하여 빌드합니다.
          flutter build apk --release --extra-front-end-options=--no-implicit-dynamic-tests --target-platform android-arm64
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
