workflows:
  android-workflow:
    name: Android Release Build
    # 마침표(.)는 저장소의 최상단(루트) 폴더를 의미합니다.
    working_directory: . 
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
