workflows:
  android-workflow:
    name: Android Release Build
    working_directory: . 
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Recreate Android and Set SDK Version
        script: |
          flutter clean
          rm -rf android
          flutter create --platforms android .
          # SDK 26 미만 에러를 해결하기 위해 버전을 강제 수정합니다.
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 26/g' android/app/build.gradle
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
