workflows:
  android-workflow:
    name: Android Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Generate App Icons
        script: |
          # 아이콘을 강제로 생성하는 핵심 명령어입니다.
          flutter pub run flutter_launcher_icons
      - name: Flutter build APK
        script: |
          # 버전을 1.0.1+3으로 올려서 새 앱으로 인식하게 합니다.
          flutter build apk --release --build-name=1.0.1 --build-number=3
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@example.com
