workflows:
  android-workflow:
    name: Over The Bike Fit Final
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Project Setup
        script: flutter create --platforms android .
      - name: Get Packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --build-number=100
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
