workflows:
  bike-fit-build:
    name: Bike Fit Final Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Initialize Project
        script: |
          flutter create . --platforms android
          # AndroidManifest.xml에 필수 블루투스 권한 자동 추가
          MANIFEST_PATH="android/app/src/main/AndroidManifest.xml"
          sed -i '' '/<application/i \
          <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" /> \
          <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" /> \
          <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> \
          <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>' $MANIFEST_PATH
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Generate Splash Screen
        script: |
          flutter pub run flutter_native_splash:create
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
